### PR TITLE
Rspec userprefs

### PR DESCRIPTION
**Pull request by josephoaks**
Completed, tests that failed were from a bigger issue with the puppet rspec which a ticket is opened.

### CODE REVIEW

**Comment by binford2k** [comment]
@puppetpirate what's the status of this? It says WIP.

**Comment by binford2k** [comment]
Ping @puppetpirate

**Comment by josephoaks** [comment]
This one was complete as far as I could, there is an open issue with puppet rspec for windows failures which are still unresolved but all the tests pass, just not the first windows run.

**Comment by binford2k** [comment]
Ok. If it's done and ready to merge, please remove the WIP. (WIP says "don't merge this, I'm still working on it.")

**Comment by binford2k** [comment]
The spec works. As soon as you remove the WIP this can be merged, @puppetpirate 

```
10:51 $ rake spec
[...]
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
..............................................

Finished in 6.71 seconds (files took 15.68 seconds to load)
46 examples, 0 failures
```

**Comment by binford2k** [comment]
ping @puppetpirate

**Pull request merged**
